"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#/home/kidneybean/Documents/PycharmProjects/DjangoBasic/DjangoProject

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9ze-!e&gt5^)&p)(o6+h)%$ut=t1ydii+uyb0^4w&yp^@3m+)9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['OnlineImageConverter2-dev.us-west-2.elasticbeanstalk.com',
                 '172.31.32.103',
                 '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'OnlineImageConverter',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'OnlineImageConverter/templates/OnlineImageConverter/')],   #THIS WORKS!!!
        'DIRS': [os.path.join(BASE_DIR, 'OnlineImageConverter/templates/OnlineImageConverter/'),
                 os.path.join(BASE_DIR, 'OnlineImageConverter/templates/StyleAssets/')],   #THIS WORKS!!!
          #  '/home/kidneybean/Documents/PycharmProjects/DjangoBasic/DjangoProject/OnlineImageConverter/templates/OnlineImageConverter/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/



STATICFILES_DIRS = [
       os.path.join(BASE_DIR, 'OnlineImageConverter/static/'),
        '/home/kidneybean/Documents/PycharmProjects/AWS_Django/DjangoProject/OnlineImageConverter/static/OnlineImageConverter/StyleAssets',
    ]

#THIS IS UNNECESSARY!!!
# TEMPLATE_DIRS = (
#     os.path.join(BASE_DIR, 'OnlineImageConverter/templates/'),
# )

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/OnlineImageConverter/start/'
LOGIN_URL = '/OnlineImageConverter/accounts/login/'

#In Development the static url looks in STATICFILES_DIRS. ie when DEBUG=True
#STATICFILES_DIRS = [os.path.join(BASE_DIR, 'OnlineImageConverter/static/')]
#In Production it looks in STATIC_ROOT (ie when DEBUG=FALSE)

#TEMPLATES = [{...'DIRS': [os.path.join(BASE_DIR, 'OnlineImageConverter/templates/OnlineImageConverter/')]...}]
# IN TEMPLATE USE: "{% static 'OnlineImageConverter/StyleAssets/main_style.css' %} "

STATIC_URL = '/static/'

STATIC_FILES_ON_S3 = os.getenv('STATIC_FILES_ON_S3')
print('STATIC_FILES_ON_S3: ', STATIC_FILES_ON_S3)
MEDIA_FILES_ON_S3 = os.getenv('MEDIA_FILES_ON_S3')
print('MEDIA_FILES_ON_S3: ', MEDIA_FILES_ON_S3)

AWS_STATIC_BUCKET_NAME = os.getenv('AWS_STATIC_BUCKET_NAME')
AWS_MEDIA_BUCKET_NAME = 'django-media-public-1337'
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')

if STATIC_FILES_ON_S3 or MEDIA_FILES_ON_S3:
    # aws settings
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STATIC_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

if STATIC_FILES_ON_S3=="True":
    # static settings for AWS S3
    AWS_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
else:
    STATIC_URL = '/static/'
    #STATIC_ROOT = 'static'

if MEDIA_FILES_ON_S3=="True":
    # s3 public media settings
    PUBLIC_MEDIA_LOCATION = 'media'
    AWS_S3_MEDIA_DOMAIN = f'{AWS_MEDIA_BUCKET_NAME}.s3.amazonaws.com'
    # MEDIA_URL = f'https://{AWS_S3_MEDIA_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    MEDIA_URL = f'https://{AWS_S3_MEDIA_DOMAIN}/'
    #DEFAULT_FILE_STORAGE = 'OnlineImageConverter.storage_backends.MediaStorage'
else:
    MEDIA_URL = '/mediafiles/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')




