# Generated by Django 2.1.1 on 2020-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineImageConverter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('album_name', models.TextField()),
                ('album_user_id', models.IntegerField()),
            ],
        ),
    ]
