# Generated by Django 2.1.1 on 2020-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineImageConverter', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_s3_bucket_prefix',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='album_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.IntegerField(null=True),
        ),
    ]
