# Generated by Django 2.1.1 on 2020-06-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineImageConverter', '0003_auto_20200602_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(default=999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
