# Generated by Django 2.1.1 on 2020-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineImageConverter', '0004_auto_20200602_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
