# Generated by Django 2.1.1 on 2020-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineImageConverter', '0005_auto_20200602_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
