# Generated by Django 2.1.1 on 2020-06-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineImageConverter', '0006_auto_20200602_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_s3_bucket_prefix',
            field=models.TextField(),
        ),
    ]
